import type { RationaleResponse } from "@/lib/types";
import { Badge, labelTone } from "./ui/Badge";

export function RationaleDisplay({ rationale }: { rationale: RationaleResponse }) {
  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50/40">
      <div className="flex items-start justify-between border-b border-amber-100 px-5 py-4">
        <div>
          <div className="text-[11px] font-medium uppercase tracking-wider text-amber-700">
            LLM Rationale (escalated)
          </div>
          <div className="mt-1 flex items-center gap-2">
            <Badge tone={labelTone(rationale.risk_level)}>{rationale.risk_level} risk</Badge>
            <Badge tone={labelTone(rationale.recommended_action)}>
              recommend: {rationale.recommended_action}
            </Badge>
            <span className="text-[11px] text-zinc-500">
              confidence {(rationale.confidence * 100).toFixed(0)}%
            </span>
          </div>
        </div>
        <div className="text-right">
          <div className="text-[11px] font-medium uppercase tracking-wider text-zinc-500">Generated by</div>
          <div className="mt-1 font-mono text-[11px] text-zinc-700">{rationale.generated_by}</div>
        </div>
      </div>
      <div className="px-5 py-4">
        <p className="text-pretty text-sm leading-relaxed text-zinc-800">{rationale.rationale}</p>
        <ul className="mt-4 space-y-1.5">
          {rationale.key_signals.map((signal, i) => (
            <li key={i} className="flex gap-2 text-xs text-zinc-700">
              <span className="mt-1.5 inline-block h-1 w-1 flex-shrink-0 rounded-full bg-amber-500" />
              <span>{signal}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
