"""
QLoRA fine-tune of Llama 3.1 8B for analyst-style fraud rationales.

Plan
----
1. Load synthetic SFT dataset from `synthetic_sft/output/rationales.jsonl`
   (generated by `generate_rationales.py`). Format: JSON-lines with fields
   {prompt, completion} where prompt encodes the transaction + top-8 SHAP
   contributions, completion is the structured rationale (matches
   `RationaleResponse` schema).
2. Load Meta-Llama-3.1-8B-Instruct with bitsandbytes 4-bit quantization
   (nf4, double quant, bf16 compute dtype).
3. Apply LoRA adapter: r=16, alpha=32, dropout=0.05, target_modules=
   q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj.
4. Train with TRL SFTTrainer for 3 epochs, batch_size=2, grad_accum=8,
   lr=2e-4, cosine schedule, warmup_ratio=0.03.
5. Held-out validation set (10%) — track loss and (after each epoch) generate
   on 50 sampled examples and run `evaluation/llm_judge.py` to score quality.
6. Save adapter weights to `artifacts/lora-v0.1/` and push to HuggingFace Hub.
7. Production serving via vLLM with the adapter merged at startup.

Hardware target: single A100 40GB or 2× RTX 4090.
"""

from pathlib import Path


def main(
    sft_dataset: Path = Path("synthetic_sft/output/rationales.jsonl"),
    output_dir: Path = Path("artifacts/lora-v0.1"),
) -> None:
    raise NotImplementedError(
        "QLoRA fine-tuning scheduled for the dedicated LLM session. See module "
        "docstring for the training recipe."
    )


if __name__ == "__main__":
    main()
